"""
Step 3: Tracking-based ROI Entry/Exit Counting.

Object identity persistence across frames is handled upstream by YOLO's
built-in tracker (ByteTrack/BoT-SORT), which assigns a stable `track_id`
to each Detection. This module consumes the tracked detection stream and:

  1. Maintains per-track state (last known centroid, "side" of ROI line).
  2. Detects line-crossing events to count objects entering / leaving.
  3. Ensures each unique track_id is counted at most once per crossing
     direction, avoiding duplicate counting across frames.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from src.detection.detector import Detection
from src.utils.logger import get_logger


@dataclass
class TrackState:
    track_id: int
    class_name: str
    last_centroid: Tuple[float, float]
    last_side: Optional[str] = None      # "before" or "after" the counting line
    counted_in: bool = False
    counted_out: bool = False
    last_seen_frame: int = 0


@dataclass
class CrossingEvent:
    track_id: int
    class_name: str
    direction: str            # "in" or "out"
    frame_index: int
    timestamp_sec: float


class ROICounter:
    """
    Counts unique tracked objects crossing a configurable line (a simplified,
    axis-aligned ROI boundary) to avoid double-counting the same vehicle
    across consecutive frames.
    """

    def __init__(self, config):
        self.cfg = config
        self.logger = get_logger("ROICounter", config.paths.logs_dir)
        self.axis = config.tracking.roi_direction_axis  # "y" or "x"
        self.line_fraction = config.tracking.roi_line_position
        self.frame_width = config.video.resize_width
        self.frame_height = config.video.resize_height

        if self.axis == "y":
            self.line_value = self.frame_height * self.line_fraction
        else:
            self.line_value = self.frame_width * self.line_fraction

        self._tracks: Dict[int, TrackState] = {}
        self.events: List[CrossingEvent] = []

    @staticmethod
    def _centroid(bbox: List[float]) -> Tuple[float, float]:
        x1, y1, x2, y2 = bbox
        return ((x1 + x2) / 2.0, (y1 + y2) / 2.0)

    def _side_of_line(self, centroid: Tuple[float, float]) -> str:
        coord = centroid[1] if self.axis == "y" else centroid[0]
        return "before" if coord < self.line_value else "after"

    def process_detections(self, detections: List[Detection]) -> List[CrossingEvent]:
        """
        Feed one frame's worth of tracked detections. Returns any new
        crossing events generated by this frame.
        """
        new_events: List[CrossingEvent] = []

        for det in detections:
            if det.track_id is None:
                continue  # cannot dedupe without a stable identity

            centroid = self._centroid(det.bbox)
            side = self._side_of_line(centroid)

            state = self._tracks.get(det.track_id)
            if state is None:
                state = TrackState(
                    track_id=det.track_id,
                    class_name=det.class_name,
                    last_centroid=centroid,
                    last_side=side,
                    last_seen_frame=det.frame_index,
                )
                self._tracks[det.track_id] = state
                continue

            if state.last_side is not None and state.last_side != side:
                # crossing event detected
                if side == "after" and not state.counted_in:
                    event = CrossingEvent(
                        track_id=det.track_id,
                        class_name=det.class_name,
                        direction="in",
                        frame_index=det.frame_index,
                        timestamp_sec=det.timestamp_sec,
                    )
                    self.events.append(event)
                    new_events.append(event)
                    state.counted_in = True
                elif side == "before" and not state.counted_out:
                    event = CrossingEvent(
                        track_id=det.track_id,
                        class_name=det.class_name,
                        direction="out",
                        frame_index=det.frame_index,
                        timestamp_sec=det.timestamp_sec,
                    )
                    self.events.append(event)
                    new_events.append(event)
                    state.counted_out = True

            state.last_centroid = centroid
            state.last_side = side
            state.last_seen_frame = det.frame_index

        return new_events

    def summary(self) -> Dict[str, int]:
        """Aggregate crossing counts by class and direction."""
        summary: Dict[str, int] = {}
        for e in self.events:
            key = f"{e.class_name}_{e.direction}"
            summary[key] = summary.get(key, 0) + 1
        return summary
